---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true

suites:
- name: default
  run_list: ["recipe[go]"]
  attributes: {}
