source 'https://rubygems.org'

gem 'chef', '~> 12'
gem 'chefspec'
gem 'foodcritic'
gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-ec2'
gem 'kitchen-digitalocean'
gem 'kitchen-docker'
gem 'winrm-transport'
gem 'guard'
gem 'guard-foodcritic'
gem 'guard-rubocop'
gem 'guard-rspec'
gem 'cookstyle'
